In [1]:
from kg_interface import KGInterface

In [2]:
import os
os.chdir("../")

In [3]:
kg = KGInterface("family")

2026-04-26 16:41:42.018 | INFO     | kg_interface:__init__:86 - Initialized KG Interface for dataset: family
2026-04-26 16:41:42.019 | INFO     | kg_interface:__init__:87 - Complete graph: 15784 triples
2026-04-26 16:41:42.019 | INFO     | kg_interface:__init__:88 - Incomplete graph: 17614 triples
2026-04-26 16:41:42.020 | INFO     | kg_interface:__init__:89 - Relations: 12 (optional)
2026-04-26 16:41:42.021 | INFO     | kg_interface:__init__:90 - Entities: 2920 (optional)

In [4]:
kg.get_1hop_triples_incomplete("444")

    head   relation tail
0    444  nephew_of  593
1    444  nephew_of  594
2    444  nephew_of  471
3    444     son_of  435
4    444     son_of  441
5    592    aunt_of  444
6   1064    aunt_of  444
7    435  father_of  444
8    441  mother_of  444
9    442  sister_of  444
10   471   uncle_of  444
11   594   uncle_of  444

In [6]:
kg.incomplete_kg[kg.incomplete_kg['head'] == "444"]

      head   relation tail
7947   444  nephew_of  593
8657   444  nephew_of  594
9839   444  nephew_of  471
13440  444     son_of  435
14410  444     son_of  441